apiVersion: v1
kind: Pod
metadata:
  name: node-app-pod
  labels:
    app: selenium-hub
spec:
  containers:
    - name: node-app
      image: ecoronado/node-naf-app
      ports:
        - containerPort: 4444 
