apiVersion: v1
kind: Pod
metadata:
  name: node-app
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: node-app
        image: docker pull ecoronado/node-naf-app
        ports:
          - containerPort: 4444 
