apiVersion: v1
kind: Service
metadata:
  name: nodeapp-service
  labels:
    name: nodeapp-service
    app: naf
spec:
  ports:
  - port: 4444 
    targetPort: 4444 
  selector:
    name: node-app-pod
    app: naf
  type: LoadBalancer
  sessionAffinity: None