apiVersion: v1
kind: Pod
metadata:
  name: node-app-pod
  labels:
    name: node-app-pod
    app: naf
spec:
  containers:
    - name: node-app
      image: ecoronado/node-naf-app
      ports:
        - containerPort: 4444 
