apiVersion: v1
kind: Pod
metadata:
  name: node-app
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:2.53.0
        ports:
          - containerPort: 4444 
