apiVersion: v1
kind: Pod
metadata:
  name: selenium-firefox-pod 
  labels:
    name: selenium-firefox-pod
    app: naf
spec:
  containers:
      - name: selenium-node-firefox
        image: selenium/node-firefox-debug:2.53.0
        ports:
          - containerPort: 5900 
        env:
          - name: HUB_PORT_4444_TCP_ADDR 
            value: "selenium-hub"
          - name: HUB_PORT_4444_TCP_PORT 
            value: "4444"