apiVersion: v1
kind: ReplicationController
metadata:
  name: selenium-hub 
  labels:
    app: automation-framework
spec:
  replicas: 1
  selector:
    app: selenium-hub
  template:
    metadata:
      labels:
        name: selenium-hub
        app: automation-framework
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub
        ports:
          - containerPort: 4444 