apiVersion: v1
kind: Service
metadata:
  name: selenium-hub-service
  labels:
    name: selenium-hub-service
    app: naf
spec:
  ports:
  - port: 4444 
    targetPort: 4444 
  selector:
    name: selenium-hub
    app: anaf
