apiVersion: v1
kind: Pod
metadata:
  name: selenium-chrome-pod
  labels:
    name: selenium-chrome-pod
    app: naf
spec:
  containers:
    - name: selenium-chrome-pod
      image: selenium/node-chrome-debug:2.53.0
      ports:
        - containerPort: 5900 
      env:
        - name: HUB_PORT_4444_TCP_ADDR 
          value: "selenium-hub"
        - name: HUB_PORT_4444_TCP_PORT 
          value: "4444"
