apiVersion: v1
kind: Pod
metadata:
  name: selenium-hub
  labels:
    name: selenium-hub
    app: naf
spec:
  containers:
    - name: selenium-hub
      image: selenium/hub:2.53.0
      ports:
        - containerPort: 4444 
